# Generated by Django 4.1 on 2022-08-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default='asd', max_length=200, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(default='asd', max_length=200, verbose_name='Message'),
            preserve_default=False,
        ),
    ]
