# Generated by Django 4.1 on 2022-08-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_our_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_team',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='our_team',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='our_team',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
    ]
