# Generated by Django 4.1 on 2022-08-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_our_team_email_our_team_facebook_our_team_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='who_are_we',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='About Us'),
        ),
    ]
