# Generated by Django 4.1 on 2022-08-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_about_who_are_we'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='who_are_we',
            field=models.TextField(default='asd', max_length=100000, verbose_name='About Us'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='our_services',
            name='service_title',
            field=models.CharField(default='asd', max_length=200, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
