# Generated by Django 4.1 on 2022-08-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_about_who_are_we_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_services',
            name='img',
            field=models.ImageField(default='asdasd', upload_to='services', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
